---
apiVersion: v1
kind: Service
metadata:
  name: socatbox
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: socatbox
  sessionAffinity: None
  type: ClusterIP
