---
apiVersion: v1
kind: Pod
metadata:
  name: curlbox
spec:
  containers:
  - name: curlbox
    image: curlimages/curl:7.78.0
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
